<?php
set_time_limit(0);
//init Joomla Framework
define( '_JEXEC', 1 );
define( 'JPATH_BASE', realpath(dirname(".")));
define( 'DS', DIRECTORY_SEPARATOR );
?><html>

<head>
	<title>Joomfish Upgrade from joomla 1.5 to joomla 2.5
	deverloped by http://joomquery.com
	</title>
<style type="text/css">
.classname {
	-moz-box-shadow:inset 0px 1px 0px 0px #f29c93;
	-webkit-box-shadow:inset 0px 1px 0px 0px #f29c93;
	box-shadow:inset 0px 1px 0px 0px #f29c93;
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #fe1a00), color-stop(1, #ce0100) );
	background:-moz-linear-gradient( center top, #fe1a00 5%, #ce0100 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#fe1a00', endColorstr='#ce0100');
	background-color:#fe1a00;
	-moz-border-radius:6px;
	-webkit-border-radius:6px;
	border-radius:6px;
	border:1px solid #d83526;
	display:inline-block;
	color:#ffffff;
	font-family:arial;
	font-size:15px;
	font-weight:bold;
	padding:6px 24px;
	text-decoration:none;
	text-shadow:1px 1px 0px #b23e35;
}.classname:hover {
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #ce0100), color-stop(1, #fe1a00) );
	background:-moz-linear-gradient( center top, #ce0100 5%, #fe1a00 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#ce0100', endColorstr='#fe1a00');
	background-color:#ce0100;
}.classname:active {
	position:relative;
	top:1px;
}
/* This imageless css button was generated by CSSButtonGenerator.com */
</style>
</head>
<body >


<div style="width:980px; margin:0 auto; border:1px solid;padding:5px;">
<h1>Migrating JoomFish Joomla 1.5 contents to FaLang Joomla 2.5 & Joomla 3.0</h1>
<p>If you are here, then you have already done the following:</p>
<ol>
<li>
Let's assume you have Joomla 1.5 installed at <b>www.domain.com</b>. You've just migrated joomla 1.5 to joomla 2.5 using component JUpgrade and have
the new joomla at <b>www.domain.com/jupgrade</b>. You've  installed <a href="http://extensions.joomla.org/extensions/languages/multi-lingual-content/18210">Falang extension</a> in the new J2.5. If so, then the other points should be by default.
</li>
<li>
The old J1.5 joomla is placed in the current folder together with this file which you are running.
</li>
<li>
The new J2.5 is placed in <b>jupgrade</b> folder and new j2.5 tables has prefix `j25_` and are placed in the same database as the old j1.5 DB.
</li>
</ol>
<p><b>NOTE: The script will show errors if running for the second and more time.</b></p>
<p><b>NOTE: You can upgrade Joomla 2.5 to J3.0 after running this script.</b></p>

<?php if (@$_GET['run'] !== 'true') { ?>
	<div style="text-alignt:center;"><a href="?run=true" class="classname">RUN MIGRATION</a></div>
<?php exit;
}
else { ?>
	<div style="text-alignt:center;"><a href="?run=true" class="classname">RERUN MIGRATION</a></div>
<?php } ?>
</div>


<div style="width:980px; margin:0 auto; text-align:center">
<?php
require_once ( JPATH_BASE .DS.'includes'.DS.'defines.php' );
require_once ( JPATH_BASE .DS.'includes'.DS.'framework.php' );
require_once( JPATH_CONFIGURATION   .DS.'configuration.php' );
require_once ( JPATH_BASE .DS.'libraries/joomla/database/database.php');
require_once ( JPATH_BASE .DS.'libraries/import.php' );
//require_once ( JPATH_BASE .DS.'libraries'.DS.'joomla'.DS.'factory.php' );

//DB Connection
$Config = new JConfig();

$option['driver']   = $Config->dbtype;   // Database driver name
$option['host']     = $Config->host;     // Database host name
$option['user']     = $Config->user;     // User for database authentication
$option['password'] = $Config->password; // Password for database authentication
$option['database'] = $Config->db;       // Database name
$option['prefix']   = $Config->dbprefix; // Database prefix (may be empty)
$Config->dbprefix_old ="jos_";
//echo $Config->dbprefix;
$db = JDatabase::getInstance($option);
$query = $db->getQuery(true);

$query = "SELECT * FROM ".$Config->dbprefix_old."jf_content ORDER by id";
$db->setQuery($query);
$rows = $db->loadObjectList();
echo 'Total: '.count($rows).'Rows';
if($rows){
	foreach ($rows as $row){
		//$insert_query = "INSERT INTO j25_jf_content VALUES (".$row->id.";'".$row->language_id."';'".$row->reference_id."';'".$row->reference_table."';'".$row->reference_field."';'".$row->value."';'".$row->original_value."';'".$row->original_text."';'".$row->modified."';'".$row->modified_by."';'".$row->published."';)";

		$fields = array($row->id, $row->language_id, $row->reference_id , $row->reference_table , $row->reference_field, $row->value, $row->original_value, $row->original_text, $row->modified, $row->modified_by, $row->published);
		foreach ($fields as $k=>$v) {
			$fields[$k] = $db->quote($v);
		}
		$insert_query = "
			INSERT INTO j25_jf_content
			VALUES (".implode(',',$fields).")";

		$db->setQuery($insert_query);
		$result = $db->query();
		if ($result !== false) {
			echo '<p style="color:green"><span>'.$row->id.'  </span><span>'.$row->reference_table.'  </span><span>'.$row->modified.'</span></p><br />';
		}
		else {
			echo '<p style="color:red">ERROR: <span>'.$row->id.'  </span><span>'.$row->reference_table.'  </span><span>'.$row->modified.'</span></p><br />';
		}
	}
}
//jos_jf_tableinfo
$query_tableinfo = "SELECT * FROM ".$Config->dbprefix_old."jf_tableinfo ORDER by id";
$db->setQuery($query_tableinfo);
$rows_tableinfo = $db->loadObjectList();
if($rows_tableinfo){
	foreach ($rows_tableinfo as $row){
		$insert_query_tableinfo = "INSERT INTO j25_jf_tableinfo VALUES (".$row->id.";'".$row->joomlatablename."';'".$row->tablepkID."')";

		$db->setQuery($insert_query_tableinfo);
		//echo '<p style="color:green"><span>'.$row->id.'  </span><span>'.$row->reference_table.'  </span><span>'.$row->modified.'</span></p><br />';
	}
}
?>
<p>
	This script developed by Mr Lamvt <br />
	Website:<a href="http://joomquery.com" title="Joomla free templates">JoomQuery.Com</a> <br />
	Website:<a href="http://www.softbuzz.net" title="Download your favorite software! - softbuzz.net">SoftBuzz.Net</a> <br />
	Updated by: <a href="http://gruz.org.ua" title="OBEC POCTE">OBEC POCTE</a> <br />

</p>
</div>
</body>
</html>
